# Generated by Django 4.1.13 on 2025-11-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brochure',
            name='file_url',
        ),
        migrations.AddField(
            model_name='brochure',
            name='file',
            field=models.FileField(blank=True, upload_to='media/uploads/brochure'),
        ),
    ]
