# Generated by Django 4.1.13 on 2025-11-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_article_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('guest', 'Guest')], db_index=True, default='user', help_text='Classification of actor: authenticated user or anonymous guest', max_length=5)),
                ('actor_identifier', models.CharField(blank=True, db_index=True, help_text='Unique identifier: email, phone, session_id, or IP address', max_length=255)),
                ('actor_name', models.CharField(blank=True, help_text='Human-readable actor name for UI display', max_length=255)),
                ('actor_metadata', models.JSONField(blank=True, help_text='Structured metadata: email, phone, device, browser, session info', null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('upload', 'Upload'), ('download', 'Download'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('approve', 'Approve'), ('reject', 'Reject'), ('submit', 'Submit'), ('send', 'Send'), ('receive', 'Receive'), ('export', 'Export'), ('import', 'Import'), ('search', 'Search'), ('filter', 'Filter')], db_index=True, help_text='Standardized operation type from ActionType enum', max_length=12)),
                ('entity', models.CharField(db_index=True, help_text='Target entity type: product, order, user, article, etc', max_length=50)),
                ('computed_entity', models.CharField(db_index=True, help_text='Full importable model path (app_label.ModelName) for direct access', max_length=100)),
                ('entity_id', models.BigIntegerField(blank=True, db_index=True, help_text='Primary key of the target entity', null=True)),
                ('entity_name', models.CharField(blank=True, help_text='Human-readable entity identifier for UI display', max_length=255)),
                ('old_values', models.JSONField(blank=True, help_text='Compressed snapshot of data before modification', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Compressed snapshot of data after modification', null=True)),
                ('changed_fields', models.JSONField(blank=True, help_text='Array of field names that were modified', null=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable activity description for audit trails')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Source IP address of the actor', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser and device information string')),
                ('extra_data', models.JSONField(blank=True, help_text='Flexible storage for additional context, metadata, or application-specific data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the activity occurred')),
                ('user', models.ForeignKey(blank=True, db_index=False, help_text='Authenticated user who performed the activity (NULL for guests)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='core.user')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='idx_actlog_created_at'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['actor_type', '-created_at'], name='idx_actlog_type_time'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['entity', 'entity_id'], name='idx_actlog_entity'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['computed_entity', 'entity_id'], name='idx_actlog_comp_ent'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-created_at'], name='idx_actlog_action_time'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['actor_identifier'], name='idx_actlog_actor_id'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['entity', '-created_at'], name='idx_actlog_ent_time'),
        ),
    ]
