# Generated by Django 4.1.13 on 2025-12-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_productvariant_sku"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE FULLTEXT INDEX idx_article_fulltext
                ON articles(title, content, meta_description, meta_keywords, tags)
            """,
            reverse_sql="DROP INDEX idx_article_fulltext ON articles",
        ),
    ]
