# Generated by Django 4.1.13 on 2025-12-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_articles_fulltext_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='idx_article_title'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='idx_article_slug'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='idx_article_published'),
        ),
    ]
