# Generated by Django 4.1.13 on 2025-12-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_productspecification_highlighted_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE FULLTEXT INDEX idx_product_fulltext
                ON products(name, description)
            """,
            reverse_sql="DROP INDEX idx_product_fulltext ON products",
        ),
        migrations.RunSQL(
            sql="""
                CREATE FULLTEXT INDEX idx_product_variant_fulltext
                ON product_variants(model, description)
            """,
            reverse_sql="DROP INDEX idx_product_variant_fulltext ON product_variants",
        ),
    ]
