# Generated by Django 4.1.13 on 2025-12-10 09:41

from django.db import migrations


def insert_specification_master_data(apps, schema_editor):
    """Insert master specification data."""
    Specification = apps.get_model('core', 'Specification')

    specifications = [
        {
            'slug': 'dimensions',
            'icon': 'box-gold',
            'label': 'Dimensions',
        },
        {
            'slug': 'texture',
            'icon': 'texture-gold',
            'label': 'Texture',
        },
        {
            'slug': 'thickness-standard',
            'icon': 'border-gold',
            'label': 'Thickness (Standard)',
        },
        {
            'slug': 'material',
            'icon': 'texture-add-gold',
            'label': 'Material',
        },
        {
            'slug': 'applications',
            'icon': 'widget-gold',
            'label': 'Applications',
        },
        {
            'slug': 'anti-slip',
            'icon': 'encrypted-gold',
            'label': 'Anti-Slip',
        },
        {
            'slug': 'certifications',
            'icon': 'workspace-premium-gold',
            'label': 'Certifications',
        },
        {
            'slug': 'colors',
            'icon': 'color-fill',
            'label': 'Colors',
        },
        {
            'slug': 'water-absorbtion',
            'icon': 'humidity-percentage',
            'label': 'Water Absorbtion',
        },
        {
            'slug': 'thickness-specific',
            'icon': 'border',
            'label': 'Thickness (Specific)',
        },
        {
            'slug': 'number-of-face',
            'icon': 'widget',
            'label': 'Number Of Face',
        },
    ]

    for spec_data in specifications:
        Specification.objects.get_or_create(
            slug=spec_data['slug'],
            defaults={
                'icon': spec_data['icon'],
                'label': spec_data['label'],
                'is_active': True,
            }
        )


def reverse_specification_master_data(apps, schema_editor):
    """Remove master specification data."""
    Specification = apps.get_model('core', 'Specification')

    slugs = [
        'dimensions', 'texture', 'thickness-standard', 'material',
        'applications', 'anti-slip', 'certifications', 'colors',
        'water-absorbtion', 'thickness-specific', 'number-of-face'
    ]

    Specification.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_productcategory_and_more'),
    ]

    operations = [
        migrations.RunPython(
            insert_specification_master_data,
            reverse_specification_master_data
        ),
    ]
