# Generated by Django 4.1.13 on 2025-12-10 09:48

from django.db import migrations


def insert_product_category_master_data(apps, schema_editor):
    """Insert master product category data."""
    ProductCategory = apps.get_model('core', 'ProductCategory')

    categories = [
        {
            'slug': 'cemento',
            'name': 'Cemento',
        },
        {
            'slug': 'classic',
            'name': 'Classic',
        },
        {
            'slug': 'granity',
            'name': 'Granity',
        },
        {
            'slug': 'marble',
            'name': 'Marble',
        },
        {
            'slug': 'stone',
            'name': 'Stone',
        },
        {
            'slug': 'wood',
            'name': 'Wood',
        },
    ]

    for category_data in categories:
        ProductCategory.objects.get_or_create(
            slug=category_data['slug'],
            defaults={
                'name': category_data['name'],
                'description': '',
                'is_active': True,
            }
        )


def reverse_product_category_master_data(apps, schema_editor):
    """Remove master product category data."""
    ProductCategory = apps.get_model('core', 'ProductCategory')

    slugs = ['cemento', 'classic', 'granity', 'marble', 'stone', 'wood']

    ProductCategory.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_data_specification_master'),
    ]

    operations = [
        migrations.RunPython(
            insert_product_category_master_data,
            reverse_product_category_master_data
        ),
    ]
