# Generated by Django 4.1.13 on 2025-12-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_data_product_category_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'ordering': ['label', '-created_at']},
        ),
        migrations.RenameField(
            model_name='productspecification',
            old_name='product_variant',
            new_name='product',
        ),
    ]
