# Generated by Django 4.1.13 on 2025-12-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_distributor_city_distributor_gmap_link_store_city_and_more'),
        ('core', '0016_alter_productcategory_options_and_more'),
    ]

    operations = [
    ]
