# Generated by Django 4.1.13 on 2025-12-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20251211_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='specification',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
