# Generated by Django 4.1.13 on 2025-12-11 16:08

from os import name
from django.db import migrations


def update_specification_master_data(apps, schema_editor):
    """Insert master specification data."""
    Specification = apps.get_model("core", "Specification")

    specifications = [
        {
            "slug": "colors",
            "icon": "color-fill",
            "name": "Colors",
            "label": "Colors",
            "order_number": 1,
        },
        {
            "slug": "water-absorbtion",
            "icon": "humidity-percentage",
            "name": "Water Absorbtion",
            "label": "Water Absorbtion",
            "order_number": 2,
        },
        {
            "slug": "thickness-specific",
            "icon": "border",
            "name": "Thickness (Specific)",
            "label": "Thickness",
            "order_number": 3,
        },
        {
            "slug": "number-of-face",
            "icon": "widget",
            "name": "Number Of Face",
            "label": "Number Of Face",
            "order_number": 4,
        },
        {
            "slug": "dimensions",
            "icon": "box-gold",
            "name": "Dimensions",
            "label": "Dimensions",
            "order_number": 5,
        },
        {
            "slug": "texture",
            "icon": "texture-gold",
            "name": "Texture",
            "label": "Texture",
            "order_number": 6,
        },
        {
            "slug": "thickness-standard",
            "icon": "border-gold",
            "name": "Thickness (Standard)",
            "label": "Thickness",
            "order_number": 7,
        },
        {
            "slug": "material",
            "icon": "texture-add-gold",
            "name": "Material",
            "label": "Material",
            "order_number": 8,
        },
        {
            "slug": "applications",
            "icon": "widget-gold",
            "name": "Applications",
            "label": "Applications",
            "order_number": 9,
        },
        {
            "slug": "anti-slip",
            "icon": "encrypted-gold",
            "name": "Anti-Slip",
            "label": "Anti-Slip",
            "order_number": 10,
        },
        {
            "slug": "certifications",
            "icon": "workspace-premium-gold",
            "name": "Certifications",
            "label": "Certifications",
            "order_number": 11,
        },
    ]

    for spec_data in specifications:
        Specification.objects.update_or_create(
            slug=spec_data["slug"],
            defaults={
                "icon": spec_data["icon"],
                "label": spec_data["label"],
                "name": spec_data["name"],
                "order_number": spec_data["order_number"],
            },
        )


def reverse_specification_master_data(apps, schema_editor):
    """Remove master specification data."""
    Specification = apps.get_model("core", "Specification")

    slugs = [
        "dimensions",
        "texture",
        "thickness-standard",
        "material",
        "applications",
        "anti-slip",
        "certifications",
        "colors",
        "water-absorbtion",
        "thickness-specific",
        "number-of-face",
    ]

    Specification.objects.filter(slug__in=slugs).update(order_number=0)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_specification_name_specification_order_number"),
    ]

    operations = [
        migrations.RunPython(
            update_specification_master_data, reverse_specification_master_data
        ),
    ]
