# Generated by Django 4.1.13 on 2025-12-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_data_update_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('no_change', 'No Change'), ('login', 'Login'), ('logout', 'Logout'), ('upload', 'Upload'), ('download', 'Download'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('approve', 'Approve'), ('reject', 'Reject'), ('submit', 'Submit'), ('send', 'Send'), ('receive', 'Receive'), ('export', 'Export'), ('import', 'Import'), ('search', 'Search'), ('filter', 'Filter')], db_index=True, help_text='Standardized operation type from ActionType enum', max_length=12),
        ),
    ]
