# Generated by Django 4.1.13 on 2025-12-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('lantai', 'Lantai'), ('dinding', 'Dinding'), ('dinding-lantai', 'Dinding & Lantai')], max_length=20),
        ),
    ]
