"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os


BASE_DIR = Path(__file__).resolve().parent.parent

SILENCED_SYSTEM_CHECKS = ["urls.W002"]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-07%ic$e*%_4g$0xfu9qo1+t%r#th52*d^&oswt@t5ky*@rm0vj",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    "*",  # Allow all hosts in development (use with caution)
]

# CORS settings for development
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "drf_spectacular",
    # Local apps
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Add if using django-cors-headers
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.request_logging.RequestLoggingMiddleware",
]

ROOT_URLCONF = "apps.urls"

# Security settings - relaxed for development
SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_BROWSER_XSS_FILTER = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# configuration for MySQL/MariaDB 10.3+
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME", "essenza_db_dev"),
        "USER": os.environ.get("DB_USER", "root"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "root"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "collation": "utf8mb4_unicode_ci",
            "init_command": (
                "SET sql_mode='STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO';"
                "SET innodb_strict_mode=1;"
                "SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;"
                "SET SESSION time_zone = '+00:00';"
            ),
            # MariaDB 10.3 compatibility settings
            "isolation_level": "read committed",
            "autocommit": True,
            "connect_timeout": 60,
            "read_timeout": 60,
            "write_timeout": 60,
        },
        "TEST": {
            "NAME": "test_essenza_dev",
            "CHARSET": "utf8mb4",
            "COLLATION": "utf8mb4_unicode_ci",
        },
    }
}

# Cache configuration for development (using dummy cache)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    }
}

# Email backend for development (console backend)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Password hashers - untuk keamanan maksimal
# https://docs.djangoproject.com/en/4.1/topics/auth/passwords/
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",  # Paling aman, pemenang PHC
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",  # Default Django
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "detailed": {
            "format": "[{asctime}] {levelname:<8} {name:<30} | {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "{levelname} | {message}",
            "style": "{",
        },
        "request": {
            "format": "[{asctime}] {levelname:<8} REQUEST | {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "detailed",
            "level": "INFO",
        },
        "request_console": {
            "class": "logging.StreamHandler",
            "formatter": "request",
            "level": "INFO",
        },
        "exception_file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "exceptions.log",
            "formatter": "detailed",
            "level": "ERROR",
        },
        "exception_console": {
            "class": "logging.StreamHandler",
            "formatter": "detailed",
            "level": "ERROR",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "core.middleware.request_logging": {
            "handlers": ["request_console"],
            "level": "INFO",
            "propagate": False,
        },
        "exception_handler": {
            "handlers": ["exception_console", "exception_file"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": [],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "WARNING",  # Hanya WARNING ke atas
            "propagate": False,
        },
    },
}


# Django REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "core.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",  # Allow any access
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_SCHEMA_CLASS": "utils.schema.CustomAutoSchema",
    "UNAUTHENTICATED_USER": None,  # No default user object
    "UNAUTHENTICATED_TOKEN": None,  # No default token object
    "EXCEPTION_HANDLER": "core.handlers.drf_exception.custom_exception_handler",
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
}

# drf-spectacular Configuration
SPECTACULAR_SETTINGS = {
    "TITLE": "Essenza Backend API",
    "DESCRIPTION": "API Documentation for Essenza Backend Application",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": False,
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "SERVE_AUTHENTICATION": [],
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": False,
        "defaultModelsExpandDepth": 1,
        "defaultModelExpandDepth": 1,
        "defaultModelRendering": "example",
        "displayRequestDuration": True,
        "docExpansion": "none",
        "filter": True,
        "showExtensions": True,
        "showCommonExtensions": True,
        "supportedSubmitMethods": ["get", "post", "put", "delete", "patch"],
        "oauth2RedirectUrl": None,
        "validatorUrl": None,  # Disable validator to avoid caching issues
    },
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {"type": "http", "scheme": "bearer", "bearerFormat": "JWT"}
        }
    },
    "REDOC_UI_SETTINGS": {
        "hideDownloadButton": False,
        "expandResponses": "all",
        "pathInMiddlePanel": True,
        "theme": {"colors": {"primary": {"main": "#2196F3"}}},
    },
    "PREPROCESSING_HOOKS": [],
    "POSTPROCESSING_HOOKS": [
        "utils.docs.add_security_schemes",
    ],
    "SCHEMA_PATH_PREFIX": "/api/",
    "DEFAULT_GENERATOR_CLASS": "drf_spectacular.generators.SchemaGenerator",
    "TAGS": [
        {"name": "General", "description": "General purpose endpoints"},
        {
            "name": "Internal / Authentication",
            "description": "Authentication related endpoints",
        },
        {
            "name": "Internal / Settings",
            "description": "Application settings management",
        },
        {
            "name": "Internal / Social Media",
            "description": "Social media links management",
        },
        {
            "name": "Internal / Menu",
            "description": "Application menu management",
        },
    ],
}

# Migration modules - Skip unwanted migrations
MIGRATION_MODULES = {
    "auth": None,  # Skip auth app migrations to avoid groups, permissions tables
    # 'contenttypes': None,  # Keep contenttypes - DRF needs it
}

# Database router to exclude certain tables
DATABASE_ROUTERS = []

# Development-specific settings
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]

# Django Debug Toolbar (if installed)
if "debug_toolbar" in INSTALLED_APPS:
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": lambda request: DEBUG,
    }

# File upload settings for development
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Time zone for development
TIME_ZONE = "Asia/Jakarta"
USE_TZ = True

# Language settings
USE_I18N = True
USE_L10N = True

# Session settings for development
SESSION_COOKIE_AGE = 86400  # 1 day
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

JWT_SECRET = os.environ.get(
    "JWT_SECRET", "Z7zl2n_ee-DKHEr7e7Dek7zV6YxVZON-ypQMUNhfm4ioYBPXtjhxCX1syq8"
)
JWT_ALGORITHM = "HS256"
# JWT_EXPIRY_SECONDS = 3600  # 1 hour
JWT_EXPIRY_SECONDS = 86400  # 1 hour
JWT_REFRESH_SIGNATURE = os.environ.get(
    "JWT_REFRESH_SIGNATURE", "JTrFGGbDCxNdf6YcjtoVpcXaw1_K4Ppt1m_YzoEZE5o"
)
JWT_FERNET_KEY = os.environ.get(
    "JWT_FERNET_KEY", "soJLqlAzc2ESzvr3NTbeZ8TqT7VgmmW5g-KUYiKyihE="
)
